-- Pinned reviewed catalog snapshot; no Supabase SQL/functions copied.
-- Source public SIDEY commit: 96f62abc0b350791de8e0d7c3b3af33f4e73dae6
-- commerce-catalog.json SHA-256: 54e2f0298c4652d113e34374bc748fda829300e327ff9dd682df316fc149884b
-- Current prices reflect final 20260916000000_starlight_upalupa_price.sql.
-- Legacy Apple offers retained for verified purchase restoration.
insert into commerce_products (id,display_name,product_description,product_kind,catalog_item_id,character_id,entitlement_key,sort_order,related_character_product_id,render_asset_id) values
    ('character_starlight_upalupa','별빛 우파루파','길 잃은 별 하나를 데려왔어요. 잘 때도 품에 꼭 안고 잔대요.','character','pixel_starlight_upalupa','pixel_starlight_upalupa','character:pixel_starlight_upalupa',10,null,null),
    ('character_guinea_pig','아기 기니피그','간식을 숨긴 곳을 잊어버렸어요. 볼이 빵빵한 걸 보니 멀리 있진 않네요.','character','pixel_guinea_pig','pixel_guinea_pig','character:pixel_guinea_pig',20,null,null),
    ('character_monkey','아기 원숭이','바나나를 나눠 주러 왔어요. 오는 길에 한 입만 먹었다는데… 반쪽이네요?','character','pixel_monkey','pixel_monkey','character:pixel_monkey',30,null,null),
    ('character_chinchilla','아기 친칠라','모래 목욕을 마치고 놀러 왔어요. 인사보다 먼저 뽀송한 털 자랑부터 해요.','character','pixel_chinchilla','pixel_chinchilla','character:pixel_chinchilla',40,null,null),
    ('character_otter','아기 수달','마음에 드는 조개를 보여 주러 왔어요. 구경은 되지만 가져가면 삐져요.','character','pixel_otter','pixel_otter','character:pixel_otter',50,null,null),
    ('character_pig','아기 돼지','간식 냄새를 따라왔다가 눌러앉았어요. 이제 여기가 자기 집인 줄 알아요.','character','pixel_pig','pixel_pig','character:pixel_pig',60,null,null),
    ('character_tree','나무','산책 나온 작은 나무예요. 잠깐 쉬랬더니 뿌리내릴 자리를 고르고 있어요.','character','pixel_tree','pixel_tree','character:pixel_tree',70,null,null),
    ('bubble_bunny_pink','핑크 토끼 말풍선','토끼 장식이 있는 분홍 말풍선','bubble','bubble_bunny_pink',null,'bubble:bubble_bunny_pink',110,null,null),
    ('bubble_butter_chick','버터 병아리 말풍선','병아리 장식이 있는 버터색 말풍선','bubble','bubble_butter_chick',null,'bubble:bubble_butter_chick',120,null,null),
    ('bubble_starry_cat','별밤 고양이 말풍선','별고양이 장식이 있는 남보라 말풍선','bubble','bubble_starry_cat',null,'bubble:bubble_starry_cat',130,null,null),
    ('throwable_bouncy_heart','통통 하트','통통 튀며 날아가는 하트 투척물','throwable','throwable_bouncy_heart',null,'throwable:throwable_bouncy_heart',210,null,'throwable_bouncy_heart'),
    ('throwable_toy_cannon','미니 대포','심지탄을 쏘는 미니 대포 투척물','throwable','throwable_toy_cannon',null,'throwable:throwable_toy_cannon',220,null,'throwable_toy_cannon'),
    ('throwable_squeaky_duck','삑삑 오리','오리가 오리를 던져요. 가족 문제는 아닌 것 같아요.','throwable','throwable_squeaky_duck',null,'throwable:throwable_squeaky_duck',230,null,'throwable_squeaky_duck'),
    ('throwable_snowflake','눈송이','맞으면 작은 결정 조각으로 흩어지는 눈송이예요.','throwable','throwable_snowflake',null,'throwable:throwable_snowflake',240,null,'throwable_snowflake'),
    ('throwable_baseball','야구공','붉은 실밥이 있는 공이 눌렸다 튕겨요.','throwable','throwable_baseball',null,'throwable:throwable_baseball',250,null,'throwable_baseball'),
    ('throwable_wakkuball','왁뿌볼','와그작! 왁뿌볼이 조각조각 부서지는 바삭한 소리를 느껴보세요.','throwable','throwable_wakkuball',null,'throwable:throwable_wakkuball',260,null,'throwable_wakkuball'),
    ('throwable_dujjonku','두쫀쿠','코코아 겉피와 초록색 속이 눌리며 바삭한 소리가 나요.','throwable','throwable_dujjonku',null,'throwable:throwable_dujjonku',270,null,'throwable_dujjonku'),
    ('throwable_mini_paprika','기니피그의 미니 파프리카','아껴 둔 간식이에요. 던진 뒤엔 3초 안에 주우면 괜찮겠죠?','throwable','throwable_mini_paprika',null,'throwable:throwable_mini_paprika',300,null,'mini_paprika'),
    ('throwable_banana','원숭이의 바나나','원숭이가 양보한 바나나예요. 양보한 게 맞는지는 아직 못 물어봤어요.','throwable','throwable_banana',null,'throwable:throwable_banana',310,null,'banana'),
    ('throwable_dust_bath_pouch','친칠라의 모래주머니','친칠라의 목욕 모래예요. 씻으라고 던지는 건… 아마 아닐 거예요.','throwable','throwable_dust_bath_pouch',null,'throwable:throwable_dust_bath_pouch',320,null,'dust_bath_pouch'),
    ('throwable_starlight_orb','별빛 우파루파의 별빛 구슬','별빛을 꾹꾹 뭉쳤어요. 하늘에서 별 하나가 없어졌다는데요?','throwable','throwable_starlight_orb',null,'throwable:throwable_starlight_orb',330,null,'starlight_orb'),
    ('throwable_clam','수달의 조개','수달이 품고 다니던 조개예요. 진주는 없고, 미련은 좀 있어요.','throwable','throwable_clam',null,'throwable:throwable_clam',340,null,'clam'),
    ('throwable_pork','아기 돼지의 돼지고기','찰진 촵! 근데 옆집 꿀꿀이가 며칠 전부터 안 보이던데…?','throwable','throwable_pork',null,'throwable:throwable_pork',350,null,'pork'),
    ('throwable_timber','나무의 작은 나무','나무가 작은 나무를 던져요. 일단 족보부터 확인해 볼까요?','throwable','throwable_timber',null,'throwable:throwable_timber',360,null,'timber'),
    ('character_shiba','시바견','산책은 다녀왔어요. 시바는 그 사실을 인정하지 않아요.','character','pixel_shiba','pixel_shiba','character:pixel_shiba',80,null,null),
    ('throwable_tennis_ball','테니스공','던질 사람은 정했어요. 주워 올 사람은 아직이요.','throwable','throwable_tennis_ball',null,'throwable:throwable_tennis_ball',370,null,'tennis_ball'),
    ('character_duck','오리','오리발 내미는 데는 자신 있어요. 진짜 오리발이거든요.','character','pixel_duck','pixel_duck','character:pixel_duck',81,null,null),
    ('character_poop','똥','누가 불렀는지는 모르겠지만, 일단 나왔어요.','character','pixel_poop','pixel_poop','character:pixel_poop',82,null,null),
    ('throwable_tissue_ball','휴지 뭉치','똥휴지인지 아닌지는 모르겠어요. 일단 피하세요!','throwable','throwable_tissue_ball',null,'throwable:throwable_tissue_ball',390,null,'tissue_ball'),
    ('character_tteokbokki','떡볶이','순한맛이라더니요. 누구 기준인지는 안 알려줬어요.','character','pixel_tteokbokki','pixel_tteokbokki','character:pixel_tteokbokki',83,null,null),
    ('throwable_fish_cake_skewer','어묵꼬치','드시라고 드린 건데 왜 휘두르세요?','throwable','throwable_fish_cake_skewer',null,'throwable:throwable_fish_cake_skewer',400,null,'fish_cake_skewer'),
    ('character_quokka','쿼카','항상 웃고 있어요. 방금 잎사귀를 던진 것도 얘예요.','character','pixel_quokka','pixel_quokka','character:pixel_quokka',84,null,null),
    ('throwable_leaf','잎사귀','쿼카의 도시락이에요. 던져도 되는지는 안 물어봤어요.','throwable','throwable_leaf',null,'throwable:throwable_leaf',410,null,'leaf');
update commerce_products set related_character_product_id='character_duck' where id='throwable_squeaky_duck';
update commerce_products set related_character_product_id='character_guinea_pig' where id='throwable_mini_paprika';
update commerce_products set related_character_product_id='character_monkey' where id='throwable_banana';
update commerce_products set related_character_product_id='character_chinchilla' where id='throwable_dust_bath_pouch';
update commerce_products set related_character_product_id='character_starlight_upalupa' where id='throwable_starlight_orb';
update commerce_products set related_character_product_id='character_otter' where id='throwable_clam';
update commerce_products set related_character_product_id='character_pig' where id='throwable_pork';
update commerce_products set related_character_product_id='character_tree' where id='throwable_timber';
update commerce_products set related_character_product_id='character_shiba' where id='throwable_tennis_ball';
update commerce_products set related_character_product_id='character_poop' where id='throwable_tissue_ball';
update commerce_products set related_character_product_id='character_tteokbokki' where id='throwable_fish_cake_skewer';
update commerce_products set related_character_product_id='character_quokka' where id='throwable_leaf';
insert into commerce_prices (product_id,amount_krw,currency,tax_inclusive) values
    ('character_starlight_upalupa',2200,'KRW',true),
    ('character_guinea_pig',1100,'KRW',true),
    ('character_monkey',1100,'KRW',true),
    ('character_chinchilla',1100,'KRW',true),
    ('character_otter',1100,'KRW',true),
    ('character_pig',1100,'KRW',true),
    ('character_tree',1100,'KRW',true),
    ('bubble_bunny_pink',2200,'KRW',true),
    ('bubble_butter_chick',2200,'KRW',true),
    ('bubble_starry_cat',2200,'KRW',true),
    ('throwable_bouncy_heart',1100,'KRW',true),
    ('throwable_toy_cannon',3300,'KRW',true),
    ('throwable_squeaky_duck',1100,'KRW',true),
    ('throwable_snowflake',1100,'KRW',true),
    ('throwable_baseball',1100,'KRW',true),
    ('throwable_wakkuball',2200,'KRW',true),
    ('throwable_dujjonku',2200,'KRW',true),
    ('throwable_mini_paprika',1100,'KRW',true),
    ('throwable_banana',1100,'KRW',true),
    ('throwable_dust_bath_pouch',1100,'KRW',true),
    ('throwable_starlight_orb',1100,'KRW',true),
    ('throwable_clam',1100,'KRW',true),
    ('throwable_pork',1100,'KRW',true),
    ('throwable_timber',1100,'KRW',true),
    ('character_shiba',1100,'KRW',true),
    ('throwable_tennis_ball',1100,'KRW',true),
    ('character_duck',1100,'KRW',true),
    ('character_poop',1100,'KRW',true),
    ('throwable_tissue_ball',1100,'KRW',true),
    ('character_tteokbokki',1100,'KRW',true),
    ('throwable_fish_cake_skewer',1100,'KRW',true),
    ('character_quokka',1100,'KRW',true),
    ('throwable_leaf',1100,'KRW',true);
insert into app_store_product_offers (store_product_id,product_id,current_offer,includes_related_throwable) values
    ('character_starlight_upalupa_solo','character_starlight_upalupa',true,false),
    ('character_starlight_upalupa','character_starlight_upalupa',false,true),
    ('character_guinea_pig_solo','character_guinea_pig',true,false),
    ('character_guinea_pig','character_guinea_pig',false,true),
    ('character_monkey_solo_4','character_monkey',true,false),
    ('character_monkey_solo_2','character_monkey',false,false),
    ('character_monkey_solo_3','character_monkey',false,false),
    ('character_monkey_solo','character_monkey',false,false),
    ('character_monkey','character_monkey',false,true),
    ('character_chinchilla_solo','character_chinchilla',true,false),
    ('character_chinchilla','character_chinchilla',false,true),
    ('character_otter','character_otter',true,false),
    ('character_pig','character_pig',true,false),
    ('character_tree_2','character_tree',true,false),
    ('character_tree','character_tree',false,false),
    ('bubble_bunny_pink','bubble_bunny_pink',true,false),
    ('bubble_butter_chick','bubble_butter_chick',true,false),
    ('bubble_starry_cat','bubble_starry_cat',true,false),
    ('throwable_bouncy_heart','throwable_bouncy_heart',true,false),
    ('throwable_toy_cannon','throwable_toy_cannon',true,false),
    ('throwable_squeaky_duck','throwable_squeaky_duck',true,false),
    ('throwable_snowflake','throwable_snowflake',true,false),
    ('throwable_baseball','throwable_baseball',true,false),
    ('throwable_wakkuball','throwable_wakkuball',true,false),
    ('throwable_dujjonku','throwable_dujjonku',true,false),
    ('throwable_mini_paprika','throwable_mini_paprika',true,false),
    ('throwable_banana','throwable_banana',true,false),
    ('throwable_dust_bath_pouch','throwable_dust_bath_pouch',true,false),
    ('throwable_starlight_orb','throwable_starlight_orb',true,false),
    ('throwable_clam_2','throwable_clam',true,false),
    ('throwable_clam','throwable_clam',false,false),
    ('throwable_pork_2','throwable_pork',true,false),
    ('throwable_pork','throwable_pork',false,false),
    ('throwable_timber','throwable_timber',true,false),
    ('character_shiba','character_shiba',true,false),
    ('throwable_tennis_ball','throwable_tennis_ball',true,false),
    ('character_duck','character_duck',true,false),
    ('character_poop','character_poop',true,false),
    ('throwable_tissue_ball','throwable_tissue_ball',true,false),
    ('character_tteokbokki','character_tteokbokki',true,false),
    ('throwable_fish_cake_skewer','throwable_fish_cake_skewer',true,false),
    ('character_quokka','character_quokka',true,false),
    ('throwable_leaf','throwable_leaf',true,false);
